version: 2.1
jobs:
  create_infrastructure:
    docker:
      - image: circleci/python:3.8.3-buster
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "fe:4c:20:b5:69:f9:2f:b6:a2:09:f1:f7:14:6b:0f:1c"
      - run:
          name: Update
          command: |
            sudo apt update
      - run:
          name: Install dependencies
          command: |
            sudo apt install ansible -y
      - run:
          name: Ansible version
          command: |
            sudo ansible --version
      - run: 
          name: Configure server
          command: |
            ansible-playbook -i inventory main-remote.yml
workflows:
  my_workflow:
    jobs:
      - create_infrastructure